QuanLyCv1/Models/NhaCungCap.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyCv1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaCungCap
    {
        public int ID { get; set; }
        public string TenNhaCungCap { get; set; }
        public string LoaiCongViec { get; set; }
        public string TenCongViec { get; set; }
        public Nullable<System.DateTime> NgayDang { get; set; }
        public Nullable<double> LuongBatDau { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<int> LoaiIdCv { get; set; }
        public string DiaChi { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> ID_TrangThai { get; set; }
    
        public virtual Loai_C_V Loai_C_V { get; set; }
        public virtual STT_TT STT_TT { get; set; }
    }
}

QuanLyCv1/Areas/Admin/Controllers/NhaCungCapController.cs
using PagedList;
using QuanLyCv1.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Data.Entity;

using System.Web.Mvc;
using System.Web.UI;
using System.Drawing.Printing;
using System.Web.UI.WebControls;

namespace QuanLyCv1.Areas.Admin.Controllers
{
    public class NhaCungCapController : Controller
    {
        private QuanLyCVEntities db = new QuanLyCVEntities();

        // GET: Admin/NhaCungCap

        
        public ActionResult DanhSach(string name, int? page, int categoryID = 0)
        {
            ViewBag.key = name;
            ViewBag.Subject = categoryID;
            var sp = db.NhaCungCaps.Include(b => b.Loai_C_V);
            if (categoryID != 0)
            {
                sp = sp.Where(c => c.LoaiIdCv == categoryID);
                page = 1;
            }
            if (!string.IsNullOrEmpty(name))
            {
                sp = sp.Where(b => b.TenCongViec.Contains(name));
                page = 1;
            }
            ViewBag.CategoryID = new SelectList(db.Loai_C_V, "ID", "LoaiCV");
            int pageSize = 5;
            int pageNumber = (page ?? 1);
            return View(sp.OrderBy(p=>p.ID).ToPagedList(pageNumber, pageSize));
           
        }
   

        [HttpPost]
        public JsonResult AutoSearch(string autoName)
        {
            var ps = db.NhaCungCaps.Where(b => b.TenCongViec.Contains(autoName)).Select(b => new { label = b.TenCongViec });
            return Json(ps, JsonRequestBehavior.AllowGet);  
        }



        public ActionResult ThemMoi()
        {
            ViewBag.LoaiIdCv = new SelectList(db.Loai_C_V, "ID", "LoaiCV");
          
            return View(new NhaCungCap() { NgayDang = DateTime.Now}) ;
        }
        public ActionResult ThemMoiLoai(int id)
        {
            return View(new Loai_C_V() { ID = id });
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult ThemMoi([Bind(Include = "ID,TenNhaCungCap,LoaiCongViec,TenCongViec,NgayDang,LuongBatDau,TrangThai,Status,HinhAnh,LoaiIdCv,DiaChi,MoTa")] NhaCungCap model, HttpPostedFileBase HinhAnh, int? id)
        {
            //check data
            model.ID_TrangThai = 1;
            if (string.IsNullOrEmpty(model.TenNhaCungCap) == true)
            {
                ModelState.AddModelError("", "Khong de trong nha cung cap");
                return View(model);

            }
            if (HinhAnh != null && HinhAnh.ContentLength > 0)
            {
               

                //model.Anh = new byte[HinhAnh.ContentLength];
                //HinhAnh.InputStream.Read(model.Anh, 0, HinhAnh.ContentLength);
                //string fileName = System.IO.Path.GetFileName(HinhAnh.FileName);
                //string url = Server.MapPath("~/Data/images/" + fileName);
                //HinhAnh.SaveAs(url);
                //model.HinhAnh = "~/Data/images/" + fileName;
               var tuongDoiUrl = "/Data/images/"; // luu data 
                var tuyetDoiUrl = Server.MapPath(tuongDoiUrl); // luu file server

                HinhAnh.SaveAs(tuyetDoiUrl + HinhAnh.FileName);
                string fullUrl = tuyetDoiUrl + HinhAnh.FileName;
                int i = 0;
                while (System.IO.File.Exists(fullUrl) == true)
                {
                    string ten = Path.GetFileNameWithoutExtension(HinhAnh.FileName);
                    string duoi = Path.GetExtension(HinhAnh.FileName);
                    fullUrl = tuyetDoiUrl + ten + "-" + i + duoi;
                    i++;
                }
                HinhAnh.SaveAs(fullUrl);
                model.HinhAnh = tuongDoiUrl + Path.GetFileName(fullUrl);
            }

            // save
            if (ModelState.IsValid)
            {
                try
                {
                   
                    //var tuongDoiUrl = "/Data/images/"; // luu data 
                    //var tuyetDoiUrl = Server.MapPath(tuongDoiUrl); // luu file server

                    //HinhAnh.SaveAs(tuyetDoiUrl + HinhAnh.FileName);
                    //string fullUrl = tuyetDoiUrl + HinhAnh.FileName;
                    //int i = 0;
                    //while (System.IO.File.Exists(fullUrl) == true)
                    //{
                    //    string ten = Path.GetFileNameWithoutExtension(HinhAnh.FileName);
                    //    string duoi = Path.GetExtension(HinhAnh.FileName);
                    //    fullUrl = tuyetDoiUrl + ten + "-" + i + duoi;
                    //    i++;
                    //}
                    //HinhAnh.SaveAs(fullUrl);

                    //string _FileName = Path.GetFileName(HinhAnh.FileName);
                    //string _path = Path.Combine(Server.MapPath("~/Data/images/"), _FileName);
                    //HinhAnh.SaveAs(_path);

                    db.NhaCungCaps.Add(model);
                    db.SaveChanges();
                    return RedirectToAction("ChiTiet", new {id = model.ID});
                }

                catch
                {
                    ModelState.AddModelError("", "Loi khong the tao");

                }
              
            }
            ViewBag.LoaiIdCv = new SelectList(db.Loai_C_V, "ID", "LoaiCV", model.LoaiIdCv);
            return View(model);

        }

        public ActionResult CapNhat(int id)
        {
            var map = new mapNhaCungCap();
            var cungCap = map.ChiTiet(id);
            ViewBag.LoaiIdCv = new SelectList(db.Loai_C_V, "ID", "LoaiCV");

            return View(cungCap);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult CapNhat([Bind(Include = "ID,TenNhaCungCap,LoaiCongViec,TenCongViec,NgayDang,LuongBatDau,TrangThai,Status,HinhAnh,LoaiIdCv,DiaChi,MoTa")] NhaCungCap model,int? id, HttpPostedFileBase fileAnh)
        {
            

            if (ModelState.IsValid)
            {
                db.Entry(model).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ChiTiet", new {id = model.ID});


            }
            ViewBag.LoaiIdCv = new SelectList(db.Loai_C_V, "ID", "LoaiCV", model.LoaiIdCv);
            return View(model);

            //if (string.IsNullOrEmpty(model.TenNhaCungCap) == true)
            //{
            //    ModelState.AddModelError("", "Khong de trong nha cung cap");
            //    return View(model);

            //}

            //// save
            //try
            //{
            //    var upDateCungCap = db.NhaCungCaps.Find(model.ID);

            //    upDateCungCap.TenNhaCungCap = model.TenNhaCungCap;
            //    upDateCungCap.TenCongViec = model.TenCongViec;
            //    upDateCungCap.LoaiIdCv = model.LoaiIdCv;
            //    upDateCungCap.NgayDang = model.NgayDang;
            //    upDateCungCap.LuongBatDau= model.LuongBatDau;

            //    db.SaveChanges();

            //    return RedirectToAction("DanhSach");

            //}
            //catch
            //{
            //    ModelState.AddModelError("", "Loi khong the tao");

            //    return View();
            //}
           

        }
        public ActionResult Xoa(int id)
        {
            var deleteCungCap = db.NhaCungCaps.Find(id);

            db.NhaCungCaps.Remove(deleteCungCap);
            db.SaveChanges();

            return RedirectToAction("DanhSach");

        }
        public ActionResult ChiTiet(int id)
        {

            var nhaCC = db.NhaCungCaps.Find(id);
            return View(nhaCC);
        }

       //public ActionResult ThemPhanLoai(int idLoai) {

       //   return View(new Loai_C_V() { ID == idLoai });
       // }
        public ActionResult CapNhatAnh(int idNhaCC)
        {
            ViewBag.idNhaCC = idNhaCC;
            return View();
        }
        [HttpPost]
        public ActionResult CapNhatAnh(int idNhaCC, HttpPostedFileBase fileAnh)
        {

            if(fileAnh == null)
            {
                ViewBag.error = "Chua chon file";
                ViewBag.idNhaCC = idNhaCC;

                return View();
            }
            if(fileAnh.ContentLength ==0)
            {
                ViewBag.error = "file khong co noi dung";
                ViewBag.idNhaCC = idNhaCC;

                return View();
            }
            var tuongDoiUrl = "/Data/images/"; // luu data 
            var tuyetDoiUrl = Server.MapPath(tuongDoiUrl); // luu file server

            fileAnh.SaveAs(tuyetDoiUrl+fileAnh.FileName);
            string fullUrl = tuyetDoiUrl+ fileAnh.FileName;
            int i = 0;
            while(System.IO.File.Exists(fullUrl)==true)
            {
                string ten = Path.GetFileNameWithoutExtension(fileAnh.FileName);
            string duoi = Path.GetExtension(fileAnh.FileName);
                fullUrl = tuyetDoiUrl+ten +"-" + i+ duoi;
                i++;
            }
            fileAnh.SaveAs(fullUrl);

            // data

            mapNhaCungCap map = new mapNhaCungCap();
            map.CapNhatAnh(idNhaCC, tuongDoiUrl + Path.GetFileName(fullUrl));

            return RedirectToAction("ChiTiet", new {id = idNhaCC});
        }

        public JsonResult CapNhatStt(int id, FormCollection collection)
        {
            var map = new mapNhaCungCap();

            var status = int.Parse(collection["status"]);
            var check = map.CapNhatTrangThai(id, status);
            return Json(new
            {
                status = check
            }, JsonRequestBehavior.AllowGet);
        }
    }
}

QuanLyCv1/Areas/Admin/Views/NhaCungCap/CapNhat.cshtml
@model QuanLyCv1.Models.NhaCungCap

@{
    ViewBag.Title = "Sua";
    Layout = "~/Areas/Admin/Views/Shared/Layout-admin.cshtml";
}
<script src="~/Areas/Admin/Content/ckeditor/ckeditor.js"></script>

<h2>Sửa nhà cung cấp </h2>
<form action="" method="post"></form>
@using (Html.BeginForm("", "", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.ID)

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })



        <div class="form-group">
            <label class="control-label col-md-2">Tên nhà cung cấp</label>

            <div class="col-md-10">
                @Html.EditorFor(model => model.TenNhaCungCap, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenNhaCungCap, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
                <label class="control-label col-md-2">Loại Công Việc</label>

                <div class="col-md-10">
                    @Html.EditorFor(model => model.LoaiIdCv, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LoaiIdCv, "", new { @class = "text-danger" })
                </div>
            </div>*@
        <div class="form-group">

            @Html.LabelFor(model => model.LoaiIdCv, "Loại Công việc", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LoaiIdCv", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LoaiIdCv, "", new { @class = "text-danger" })
                @*<select name="ID" class="form-control">
                        @foreach (var item in nhaCungCap)
                        {
                            <option value="@item.ID" @Html.Raw(item.ID == Model.LoaiIdCv ? "selected" : "")>@item.LoaiCV</option>
                        }
                    </select>*@

            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-md-6">Tên Công Việc</label>
            <div class="col-md-10">
                @Html.EditorFor(model => model.TenCongViec, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TenCongViec, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            <div class="form-group col-md-4">
                <label class="control-label col-md-4">Ngày Đăng</label>

                <div class="col-md-10">
                    <input name="NgayDang" class="form-control" value="@String.Format("{0:d}",Model.NgayDang)" type="datetime" readonly />
                    @Html.ValidationMessageFor(model => model.NgayDang, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group col-md-4">
                <label class="control-label col-md-4">Lương khởi điểm</label>

                <div class="col-md-10">
                    @Html.EditorFor(model => model.LuongBatDau, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LuongBatDau, "", new { @class = "text-danger" })
                </div>
            </div>


        </div>
        @*<div class="form-group">
                <label class="control-label col-md-4">Hình ảnh</label>

                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.HinhAnh, null, new { type = "file", @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.HinhAnh, "", new { @class = "text-danger" })
                </div>
            </div>*@
        <div class="form-group">
            <label class="control-label col-md-4">Mô tả công việc</label>

            <div class="col-md-10">
                @Html.TextAreaFor(model => model.MoTa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MoTa, "", new { @class = "text-danger" })
            </div>
            <script>
                CKEDITOR.replace("MoTa");
            </script>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Cập nhật" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="~/Admin/NhaCungCap/DanhSach">Trở lại danh sách</a>
</div>

QuanLyCv1/Areas/Admin/Views/NhaCungCap/CapNhatAnh.cshtml
@{
    ViewBag.Title = "CapNhatAnh";
    Layout = "~/Areas/Admin/Views/Shared/Layout-admin.cshtml";
}

<div class="col-md-12 pt-4">

    <h2>Cập nhật hình ảnh</h2>

   
    <form method="post" enctype="multipart/form-data">
        <input type="hidden" name="idNhaCC" value="@ViewBag.idNhaCC" />
        <p>
            <label>Chọn ảnh</label> <br />
            <input type="file" name="fileAnh" />
        </p>
        
        <button class="btn mt-3  btn-success">Tải ảnh lên</button>
        <p style="color:red">
            @ViewBag.error
        </p>
    </form>

</div>

QuanLyCv1/Areas/Admin/Views/NhaCungCap/ChiTiet.cshtml
@model QuanLyCv1.Models.NhaCungCap

@{
    ViewBag.Title = "Chi Tiet San Pham";
    Layout = "~/Areas/Admin/Views/Shared/Layout-admin.cshtml";
}


<div class="row">

    <div class="col-md-12">
        <h2>Chi Tiet Công Việc</h2>

        <h4>Nhà cung cấp số @Model.ID</h4>
        <hr />

    </div>
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-3">
                <h3>Hình ảnh</h3>
                <img src="@Model.HinhAnh" style="width:200px"/>
                <p>
                    <a href="/Admin/NhaCungCap/CapNhatAnh?idNhaCC=@Model.ID" class="pull-right mt-3 btn btn-danger">Tải ảnh lên</a>
                </p>
            </div>
            <div class="col-md-6">
                <h3 class="text-center">Thông tin chi tiết</h3> 
                <table class="table table-bordered">
                    <tr>

                        <td class="h4">
                            Tên nhà cung cấp
                        </td>
                        <td>
                            @Model.TenNhaCungCap
                        </td>
                    </tr>

                    <tr>
                        <td class="h4">
                            Loại công việc
                        </td>
                        <td>
                            @Model.Loai_C_V.LoaiCV
                        </td>
                    </tr>

                    <tr>

                        <td class="h4">
                            Tên công việc
                        </td>
                        <td>
                            @Model.TenCongViec
                        </td>
                    </tr>

                    <tr>
                        <td class="h4">
                            Ngày đăng
                        </td>

                        <td >
                            @String.Format("{0:d}", Model.NgayDang)
                        </td>
                    </tr>

                    <tr>
                        <td class="h4">
                            Lương khởi điểm
                        </td>

                        <td >
                            @String.Format("{0:0,0}", Model.LuongBatDau)<sup>đ</sup>
                        </td>
                    </tr>
                    <tr>
                        <td class="h4">
                            Trạng thái
                        </td>
                        <td>
                            @if (Model.ID_TrangThai == 1)
                            {
                                <span class="btn btn-success">@Model.STT_TT.Loai_Trang_Thai</span>
                            }
                            else
                            {
                        <span class="btn btn-danger">@Model.STT_TT.Loai_Trang_Thai</span>
                                        }
                           @* @Html.Raw(Model. == 0 ? " <span class='btn btn-danger'>Hết hạn</span>" : "<span class='btn btn-success'>Đang tuyển</span>")*@

                        </td>
                    </tr>
                    <tr>
                        <td class="h4">Mô tả</td>
                        <td>
                            @Html.Raw(Model.MoTa)
                        </td>
                    </tr>

                </table>

            </div>
            <div class="col-md-3 text-center ">
                <h3>Chỉnh sửa Công Việc</h3> 
                <hr />
                <p class="text-center">
                    <a href="~/Admin/NhaCungCap/CapNhat?id=@Model.ID">Chỉnh sửa</a>
                </p>
            </div>
        </div>

    </div>
</div>


<div>
</div>
<p>
    <a href="~/Admin/NhaCungCap/DanhSach">Trở lại danh sách</a>

</p>

QuanLyCv1/Areas/Admin/Views/NhaCungCap/DanhSach.cshtml
@model PagedList.IPagedList<QuanLyCv1.Models.NhaCungCap>

@using PagedList.Mvc;
@{
    ViewBag.Title = "Danh Sách Việc Làm";
    Layout = "~/Areas/Admin/Views/Shared/Layout-admin.cshtml";
}
<script src="~/Areas/Admin/Content/plugins/jquery/dist/jquery.min.js"></script>
<script src="~/Areas/Admin/Content/plugins/bootstrap/dist/js/bootstrap.min.js"></script>
@section jsFooter{
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script>
        $(".btn-view-details").off("click").on("click", function (e) {
            e.preventDefault();
            var id = $(this).data("id");
            $("#Modal-" + id).modal();
        });


        $(document).ready(function () {
            $(".change-status-bill").off("click").on("click", function (event) {
                event.preventDefault();
                var id = $(this).data("id");

                var status = $(this).data("status");

                if (status == 4) {

                    Swal.fire({
                        icon: 'error',
                        title: 'Xin lỗi hàng đã chốt đơn',
                        toast: true,
                    })
                    return;
                }

                Swal.fire({
                    title: 'Đổi trạng thái!',
                    type: 'success',
                    toast: true,

                    showCloseButton: true,
                    showCancelButton: true,
                    showDenyButton: true,
                    allowEscapeKey: true,
                    allowOutsideClick: true,

                    confirmButtonText: 'Đang tuyển',
                    confirmButtonAriaLabel: '1',
                    confirmButtonColor: 'green',

                    denyButtonText: 'Hết Hạn',
                    denyButtonAriaLabel: '2',
                    denyButtonColor: "red",

                }).then((result) => {
                    var confirm;
                    if (result.isConfirmed) {
                        confirm = 1;
                    }
                    else {
                        confirm = 2;
                    }
                    if (status != confirm) {
                        $.ajax({
                            url: '/admin/NhaCungCap/CapNhatStt/' + id,
                            type: 'POST',
                            dataType: 'json',
                            data: {
                                status: confirm
                            },
                            success: function (data) {
                                location.href = "/admin/NhaCungCap/DanhSach";
                            }
                        })
                    }
                });
            });
        });</script>
}
<style>
    .badge {
        cursor: pointer;
        font-size: 20px;
    }
</style>
<style>
    .ul.pagination {
        display: inline-block;
        padding: 0;
        margin: 0;
    }

    ul.pagination li {
        display: inline;
        cursor: pointer;
        border: 1px solid green;
    }

        ul.pagination li a {
            color: black;
            float: left;
            padding: 8px 16px;
            text-decoration: none;
            transition: background-color .3s;
        }

            ul.pagination li a.active {
                background-color: #4CAF50;
                color: white;
            }

            ul.pagination li a:hover:not(.active) {
                background-color: #ddd;
            }
</style>

<a class="btn btn-dark mb-3" href="~/Admin/NhaCungCap/ThemMoi">Thêm mới</a>
<a class="btn btn-success mb-3" href="~/Admin/Loai_C_V/Create">Thêm mới loại công việc</a>



<div class="row">
    <div class="col-md-12">
        <h2>Danh sách nhà cung cấp việc làm</h2>
    </div>

    <div class="col-md-12 mb-3">

        @using (Html.BeginForm("DanhSach", "NhaCungCap", FormMethod.Get, new { @class = "form-inline" }))
        {

            <div class="input-group mb-3" style="width:50%">

                <label class="mr-2">Chọn theo danh mục  </label>
                @Html.DropDownList("CategoryID", "----------Tất Cả----------")
                <hr />
                <input type="Text" class="form-control mx-sm-3" value="@ViewBag.key" name="name" placeholder="Tên công việc">
                <input type="submit" class="btn btn-success ml-2" value="Tìm Kiếm">

            </div>


        }


    </div>

    <div class="col-md-12">
        <div class="h3">
            Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) / @Model.PageCount

        </div>
        <table class="table-bordered table table-light">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">
                        ID
                    </th>
                    <th scope="col">
                        Tên Nhà Cung Cấp
                    </th>
                    <th scope="col">
                        Hinh ảnh nhà Cung Cấp
                    </th>

                    <th scope="col">
                        Loại Công Việc
                    </th>
                    <th scope="col">
                        Tên công việc
                    </th>
                    <th scope="col">
                        Ngày bắt đầu đăng
                    </th>
                    <th scope="col">
                        Lương khởi điểm
                    </th>
                    <th scope="col">
                        Trạng thái
                    </th>
                    <th scope="col">
                        Mô tả
                    </th>
                    <th scope="col">
                        Tùy chỉnh
                    </th>

                </tr>
            </thead>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.ID
                    </td>
                    <td>
                        <a href="/Admin/NhaCungCap/ChiTiet?id=@item.ID">@item.TenNhaCungCap</a>
                    </td>

                    <td>
                        <img src="@item.HinhAnh" style="width:40%; height: 100px;" />
                    </td>
                    <td>
                        @if (item.LoaiIdCv == null)
                        {
                            <span>Chưa có loại danh mục</span>
                        }
                        else
                        {
                            @item.Loai_C_V.LoaiCV
                        }
                    </td>
                    <td>
                        @item.TenCongViec
                    </td>
                    <td>
                        @String.Format("{0:d}", item.NgayDang)
                    </td>
                    <td>
                        @String.Format("{0:0,0}", item.LuongBatDau)<sup>đ</sup>
                    </td>
                    <td>

                        @if (item.ID_TrangThai == 1)
                        {
                            <span data-id="@item.ID" data-status="@item.ID_TrangThai" class="btn badge change-status-bill btn-success">
                                @item.STT_TT.Loai_Trang_Thai
                            </span>
                        }
                        else
                        {
                            <span data-id="@item.ID" data-status="@item.ID_TrangThai" class="btn badge change-status-bill btn-danger">
                                @item.STT_TT.Loai_Trang_Thai
                            </span>
                        }
                    </td>
                    <td>
                        @Html.Raw(item.MoTa)
                    </td>
                    <td>
                        <a href="~/Admin/NhaCungCap/CapNhat?id=@item.ID">Sửa</a> |
                        <a href="~/Admin/NhaCungCap/Xoa?id=@item.ID" style="color:red">Xóa</a>

                    </td>
                </tr>
            }



        </table>

        <div class="pagination h3 ">
            @Html.PagedListPager(Model, page => Url.Action("DanhSach",
           new { page }))

        </div>

        <div class="modal fade" id="status-modal" tabindex="-1" role="dialog" aria-labelledby="status-modal-label" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="status-modal-label">Cập nhật trạng thái sản phẩm</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form action="#" method="post">
                            <div class="form-group">
                                <label for="product-status">Trạng thái sản phẩm</label>
                                <select class="form-control" id="product-status" name="product-status">
                                    @foreach (var stt in Model)
                                    {
                                        <option value="@stt.STT_TT.ID_STT">@stt.STT_TT.Loai_Trang_Thai</option>

                                    }

                                    @*<option value="2">Hết hàng</option>
                                        <option value="3">Đang giao</option>*@
                                </select>
                            </div>
                            <input type="hidden" name="product-id" value="#product-id#">
                        </form>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Đóng</button>
                        <button type="button" class="btn btn-primary" id="save-status-button">Lưu</button>
                    </div>
                </div>
            </div>
        </div>


    </div>
</div>

@section jsauto{
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(document).ready(function () {
            $("#txtProduct").autocomplete({
                source: function (request, response) {
                    $.ajax({
                        url: "/NhaCungCap/AutoSearch",
                        type: "POST",
                        dataType: "json",
                        data: { name: request.term },
                        success: function (data) {
                            response($.map(data, function (item) {
                                return { label: item.label };
                            }));
                        }
                    });
                },
                minLength: 1
            });
        });
    </script>


}